/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.ejercicio_var_6;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Scanner miScan = new Scanner(System.in);
        
        System.out.println("Introduzca el precio de la factura: ");
        int factura = miScan.nextInt();
        
        double iva = factura * 0.21;
        double coniva = factura + iva;
        
        System.out.println("La factura con iva es: " + coniva);

    }
}
